name: Lint

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Check out quietly
        run: git clone --quiet --depth 1 --branch "$GITHUB_HEAD_REF" "https://github.com/$GITHUB_REPOSITORY.git" .

      - name: Lint Markdown
        env:
          NPM_CONFIG_IGNORE_SCRIPTS: "true"
        run: npx --yes markdownlint-cli2@0.23.1 "**/*.md" "#.git"
